### ISSUE TITLE
@weight-array to small, if numbers are not consequtive

### ISSUE THREAD

**Issue by mlujr** [jaredbeck/graph_matching#11]
in lib/graph_matching/graph/weighted.rb: 

in constructor [] calculate the maximum index 
  max_idx = weightless_edges.map { |e| e.max}.max + 1
  g.init_weights(max_idx)

and add a paramter to init_weights with default
 
def init_weights(e=num_vertices)
        @weight = Array.new(e) { |_| Array.new(e) }
end

**Comment by jaredbeck** [comment]
Hi! It sounds like you have a specific change you'd like to suggest. If so, can you make a PR with tests, please?

**Comment by mlujr** [comment]
created a pull request with simple test
