### ISSUE TITLE
Gem not published

### ISSUE THREAD

**Issue by oggy** [jaredbeck/graph_matching#2]
I could do so myself of course, but thought I'd give you the honors. :)

Thanks for the lib!

**Comment by jaredbeck** [comment]
Sorry, just noticed this.  I want to publish a gem, but I'm still finalizing the API.  I suppose I could do a pre-1.0 release if that would be helpful.

**Comment by jaredbeck** [comment]
I pushed a 0.0.1 release.

https://rubygems.org/gems/graph_matching

Enjoy!  Thanks for trying it out.
