### ISSUE TITLE
max cardinality?

### ISSUE THREAD

**Issue by jmanian** [jaredbeck/graph_matching#3]
Hi, this isn't an issue, just a question really. I want to make sure I understand what `max_cardinality` means in the 4th algorithm.

My understanding is that it makes sure to produce the maximum number of possible edges, even if there are solutions with fewer edges that produce greater total weight.

So for instance if the graph has 100 nodes, and every node has an edge to every other node, then if you use `max_cardinality=true` the solution will necessarily have 50 edges. Whereas if `max_cardinality=false` then there won't necessarily be 50 edges. (Although in this example, where all edges exist, it seems this could only happen if some of the weights are 0 or negative.)

Do I have this correct?

**Comment by jaredbeck** [comment]
Hi Jeff. It's been a while, so I had to look this up.

> My understanding is that it makes sure to produce the maximum number of possible edges, even if there are solutions with fewer edges that produce greater total weight.

I believe that's correct. From the comments in Van Rantwijk's python implementation:

>  If "maxcardinality" is true, only maximum-cardinality matchings are considered as solutions.
> https://github.com/jaredbeck/graph_matching/blob/master/research/van_rantwijk/mwmatching.py#L44

**Comment by jaredbeck** [comment]
Also:

> A maximum matching (also known as maximum-cardinality matching) is a matching that contains the largest possible number of edges.
> https://en.wikipedia.org/wiki/Matching_(graph_theory)

i.e. The **cardinality** of a matching is the number of edges matched.
